### ISSUE TITLE
error code 1

### ISSUE THREAD

**Issue by darkdawn29** [justinsoon/Destiny2#1]
while compiling the build no matter what it ends with error code 1.  i did remove Read only from the folders yet  the same issue. and the ones which are pre compiled , the skype app deletes itself. without showing anything.

thank you

**Comment by justinsoon** [comment]
If you are unable to find a simple solution to the issue in the source code, I worry you will have a challenging time setting up the aim assistance. I'll give you a hint... Look at Program.cs 

As for any other errors, I will be unable to assist you since this project has been discontinued due to a lack of interest.

**Comment by justinsoon** [comment]
It maybe not be paster friendly for you, but I just re-downloaded the sln and was able to compile and fix the error you described. Check your configuration manager.

**Comment by darkdawn29** [comment]
i was able to fix the issue , tho when i run program it does nothing , the Skype.exe with skypeit.dll when i go ingame i did press F5 and f8. i dont know what im doing. small hint would work.

**Comment by darkdawn29** [comment]
if possible can you pre compile once and send,
thank you for your time
